import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadPlaywright } from "./playwright.mjs";
import { serve } from "./serve.mjs";
const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const { chromium } = loadPlaywright(require, ROOT);
const server = await serve(5179);
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 820 } });
const errors = [];
page.on("pageerror", (e) => errors.push("pageerror: " + e.message));
page.on("console", (m) => { if (m.type() === "error") errors.push("console: " + m.text()); });
await page.goto("http://localhost:5179/index.html");
await page.waitForSelector("body.ready", { timeout: 15000 }).catch(() => errors.push("not ready"));
await page.waitForTimeout(800);
await page.screenshot({ path: path.join(ROOT, "build/shot-start.png") });
console.log(errors.join("\n") || "nessun errore");
await browser.close(); server.close();
